; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp8266]
platform = espressif8266
board = d1
framework = arduino
lib_deps = 
	bblanchon/ArduinoJson@^7.0.4
	esphome/ESPAsyncWebServer-esphome@^3.2.2
	adafruit/DHT sensor library@^1.4.7
	adafruit/Adafruit SSD1306@^2.5.17
build_flags = 
	'-D__VERSION=0.1'
	'-DENABLE_ACTIONS=0'
	'-DENABLE_HOOKS=0'
lib_extra_dirs = /home/pobopo/projects/smart_thing/smart_thing_lib/lib
monitor_speed = 115200
upload_protocol = espota
upload_port = 192.168.0.140